import React,{useEffect,useMemo,useState} from "react";
import {Home,CalendarRange,TrendingUp,Settings,ChevronLeft,ChevronRight,Plus,Trash2,PiggyBank,Landmark,Sparkles,WalletCards,Download,Copy,CheckCircle2,CircleDollarSign,Sun,Moon,SunMoon,X} from "lucide-react";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,LineChart,Line,CartesianGrid} from "recharts";

const STORAGE_KEY="tracker-risparmi-local-v1";
const THEME_KEY="tracker-risparmi-theme-v1";
const monthNames=["Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre","Dicembre"];
const monthShort=["GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC"];
const euro=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"});
const money=n=>euro.format(Number.isFinite(n)?n:0);
const emptyMonths=()=>Array.from({length:12},()=>({salary:0,extras:[]}));
const makeYear=from=>({percentages:from?{...from.percentages}:{essential:50,savings:30,wants:20},extrasToSavings:from?from.extrasToSavings:true,months:emptyMonths()});
const currentYear=()=>Math.max(2026,new Date().getFullYear());
const initialData=()=>({version:1,years:{[String(currentYear())]:makeYear()}});
function restoreFromHash(){try{const m=location.hash.match(/^#restore=([A-Za-z0-9_-]+)$/);if(!m)return false;const b64=m[1].replace(/-/g,"+").replace(/_/g,"/");const pad=b64+"=".repeat((4-b64.length%4)%4);const bytes=Uint8Array.from(atob(pad),ch=>ch.charCodeAt(0));const json=new TextDecoder().decode(bytes);const x=JSON.parse(json);if(!x?.years||typeof x.years!=="object")throw new Error("invalid");localStorage.setItem(STORAGE_KEY,JSON.stringify(x));history.replaceState(null,"",location.pathname+location.search);return true}catch{history.replaceState(null,"",location.pathname+location.search);return false}}
function safeLoad(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(!x?.years)return initialData();const years=Object.fromEntries(Object.entries(x.years).filter(([y])=>Number(y)>=2026));return {...x,years:Object.keys(years).length?years:{"2026":makeYear()}}}catch{return initialData()}}
function calcMonth(y,m){const extra=m.extras.reduce((s,x)=>s+Number(x.amount||0),0),salary=Number(m.salary||0),total=salary+extra,basis=y.extrasToSavings?salary:total;const essential=Math.round(basis*y.percentages.essential/100),baseSavings=Math.round(basis*y.percentages.savings/100),wants=Math.round(basis*y.percentages.wants/100);return{salary,extra,total,essential,savings:baseSavings+(y.extrasToSavings?extra:0),wants}}
function calcYear(y){return y.months.map(m=>calcMonth(y,m)).reduce((a,m)=>({salary:a.salary+m.salary,extra:a.extra+m.extra,total:a.total+m.total,essential:a.essential+m.essential,savings:a.savings+m.savings,wants:a.wants+m.wants}),{salary:0,extra:0,total:0,essential:0,savings:0,wants:0})}
const makeId=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();

export default function App(){
 const now=new Date();
 const [data,setData]=useState(()=>{restoreFromHash();return safeLoad()});
 const [selectedYear,setSelectedYear]=useState(()=>{const y=String(currentYear());return data.years[y]?y:Object.keys(data.years).sort().at(-1)});
 const [monthIndex,setMonthIndex]=useState(now.getMonth());
 const [view,setView]=useState("home");
 const [extraOpen,setExtraOpen]=useState(false);
 const [extraAmount,setExtraAmount]=useState("");
 const [extraDescription,setExtraDescription]=useState("");
 const [extraDate,setExtraDate]=useState(now.toISOString().slice(0,10));
 const [notice,setNotice]=useState("");
 const [theme,setTheme]=useState(()=>localStorage.getItem(THEME_KEY)||"auto");
 const [themeMenu,setThemeMenu]=useState(false);
 const year=data.years[selectedYear];
 const [pct,setPct]=useState({...year.percentages});
 useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(data)),[data]);
 useEffect(()=>setPct({...data.years[selectedYear].percentages}),[selectedYear,data.years]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),2600);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{localStorage.setItem(THEME_KEY,theme);const dark=theme==="dark"||(theme==="auto"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",dark);if(theme!=="auto")return;const mq=matchMedia("(prefers-color-scheme: dark)");const fn=e=>document.documentElement.classList.toggle("dark",e.matches);mq.addEventListener?.("change",fn);return()=>mq.removeEventListener?.("change",fn)},[theme]);
 useEffect(()=>{if(view!=="home")return;const t=setTimeout(()=>document.querySelector('[data-month-index="'+monthIndex+'"]')?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"}),60);return()=>clearTimeout(t)},[monthIndex,view]);
 const month=year.months[monthIndex],current=useMemo(()=>calcMonth(year,month),[year,month]),annual=useMemo(()=>calcYear(year),[year]);
 const updateYear=fn=>setData(p=>({...p,years:{...p.years,[selectedYear]:fn(p.years[selectedYear])}}));
 const setSalary=v=>updateYear(y=>({...y,months:y.months.map((m,i)=>i===monthIndex?{...m,salary:v}:m)}));
 const moveYear=d=>{const target=String(Number(selectedYear)+d);if(Number(target)<2026)return;setData(p=>p.years[target]?p:{...p,years:{...p.years,[target]:makeYear(p.years[selectedYear])}});setSelectedYear(target)};
 const addExtra=()=>{const amount=Number(extraAmount.replace(",","."));if(!Number.isFinite(amount)||amount<=0){setNotice("Inserisci un importo valido");return}const x={id:makeId(),amount,description:extraDescription.trim()||"Entrata extra",date:extraDate||new Date().toISOString().slice(0,10)};updateYear(y=>({...y,months:y.months.map((m,i)=>i===monthIndex?{...m,extras:[...m.extras,x]}:m)}));setExtraAmount("");setExtraDescription("");setExtraOpen(false);setNotice("Entrata aggiunta")};
 const removeExtra=id=>updateYear(y=>({...y,months:y.months.map((m,i)=>i===monthIndex?{...m,extras:m.extras.filter(x=>x.id!==id)}:m)}));
 const savePercentages=()=>{const t=pct.essential+pct.savings+pct.wants;if(Math.abs(t-100)>.001||Object.values(pct).some(v=>v<0)){setNotice("Le percentuali devono sommare 100%");return}updateYear(y=>({...y,percentages:{...pct}}));setNotice("Percentuali salvate")};
 const copyPrevious=()=>{const p=data.years[String(Number(selectedYear)-1)];if(!p){setNotice("Nessun anno precedente disponibile");return}setPct({...p.percentages});updateYear(y=>({...y,percentages:{...p.percentages},extrasToSavings:p.extrasToSavings}));setNotice("Impostazioni copiate")};
 const exportBackup=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="tracker-risparmi-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(u);setNotice("Backup esportato")};
 const importRestoreCode=()=>{const code=window.prompt("Incolla il codice di ripristino");if(!code)return;try{const clean=code.trim().replace(/^#?restore=/,"");const b64=clean.replace(/-/g,"+").replace(/_/g,"/");const pad=b64+"=".repeat((4-b64.length%4)%4);const bytes=Uint8Array.from(atob(pad),ch=>ch.charCodeAt(0));const json=new TextDecoder().decode(bytes);const x=JSON.parse(json);if(!x?.years||typeof x.years!=="object")throw new Error("invalid");localStorage.setItem(STORAGE_KEY,JSON.stringify(x));location.reload()}catch{setNotice("Codice di ripristino non valido")}};
 const deleteYear=()=>{const keys=Object.keys(data.years);if(keys.length<=1){setNotice("Deve rimanere almeno un anno");return}if(!confirm("Eliminare tutti i dati del "+selectedYear+"?"))return;const next={...data.years};delete next[selectedYear];const f=Object.keys(next).sort().at(-1);setData({...data,years:next});setSelectedYear(f)};
 const annualChart=year.months.map((m,i)=>{const c=calcMonth(year,m);return{name:monthShort[i],entrate:Math.round(c.total),risparmi:Math.round(c.savings)}});
 let cum=0;const cumulativeChart=year.months.map((m,i)=>{cum+=calcMonth(year,m).savings;return{name:monthShort[i],risparmi:Math.round(cum)}});
 const historyData=Object.keys(data.years).sort().map(y=>{const t=calcYear(data.years[y]);return{year:y,entrate:Math.round(t.total),risparmi:Math.round(t.savings)}}),historySavings=historyData.reduce((s,y)=>s+y.risparmi,0);
 const ThemeIcon=theme==="dark"?Moon:theme==="light"?Sun:SunMoon;
 return <div className="app">
  <header className="header"><div><span className="kicker">TRACKER RISPARMI</span><h1>{view==="home"?"Questo mese":view==="year"?"Questo anno":view==="history"?"Storico":"Impostazioni"}</h1></div>
   <div className="headerActions"><div className="themeWrap"><button className="iconBtn themeBtn" onClick={()=>setThemeMenu(v=>!v)} aria-label="Tema"><ThemeIcon size={19}/></button>{themeMenu&&<div className="themeMenu">{[["light",Sun,"Chiaro"],["dark",Moon,"Scuro"],["auto",SunMoon,"Auto"]].map(([m,I,l])=><button key={m} className={theme===m?"themeChoice activeChoice":"themeChoice"} onClick={()=>{setTheme(m);setThemeMenu(false)}}><I size={16}/>{l}</button>)}</div>}</div>
   <div className="yearPicker"><button className="iconBtn" onClick={()=>moveYear(-1)} disabled={Number(selectedYear)<=2026}><ChevronLeft size={18}/></button><strong>{selectedYear}</strong><button className="iconBtn" onClick={()=>moveYear(1)}><ChevronRight size={18}/></button></div></div></header>
  <main className="main">
   {view==="home"&&<><div className="monthStrip">{monthShort.map((m,i)=><button key={m} data-month-index={i} className={i===monthIndex?"monthActive":"monthButton"} onClick={()=>setMonthIndex(i)}>{m}</button>)}</div>
    <section className="hero"><div className="heroTop"><span>{monthNames[monthIndex]} {selectedYear}</span><span className="statusPill">ENTRATE</span></div><div className="heroAmount">{money(current.total)}</div><div className="heroBreakdown">Stipendio {money(current.salary)} · Extra {money(current.extra)}</div><div className="allocationTrack"><span style={{width:year.percentages.essential+"%"}} className="segmentEssential"/><span style={{width:year.percentages.savings+"%"}} className="segmentSavings"/><span style={{width:year.percentages.wants+"%"}} className="segmentWants"/></div></section>
    <div className="sectionTitle"><h2>Entrate</h2><span>Salvataggio automatico</span></div><section className="card"><div className="inputRow"><div><strong>Stipendio mensile</strong><span>Netto disponibile</span></div><div className="amountInput"><span>€</span><input type="number" min="0" step=".01" value={month.salary||""} onChange={e=>setSalary(Number(e.target.value))} placeholder="0,00"/></div></div><div className="rule"/><div className="inputRow"><div><strong>Entrate extra</strong><span>{month.extras.length?month.extras.length+" "+(month.extras.length===1?"voce":"voci"):"Nessuna voce"}</span></div><button className="btn small" onClick={()=>setExtraOpen(true)}><Plus size={16}/>Aggiungi</button></div>{!!month.extras.length&&<div className="extraList">{month.extras.map(x=><div className="extraItem" key={x.id}><div><strong>{x.description}</strong><span>{new Date(x.date+"T12:00:00").toLocaleDateString("it-IT")}</span></div><div className="extraRight"><b>+{money(x.amount)}</b><button className="iconBtn" onClick={()=>removeExtra(x.id)}><Trash2 size={15}/></button></div></div>)}</div>}</section>
    <div className="sectionTitle"><h2>Ripartizione</h2><button onClick={()=>setView("settings")}>Modifica %</button></div><div className="allocationGrid"><article className="allocationCard allocationEssential"><Landmark/><span>Essenziale · {year.percentages.essential}%</span><strong>{money(current.essential)}</strong></article><article className="allocationCard allocationSavings"><PiggyBank/><span>Risparmi · {year.percentages.savings}%</span><strong>{money(current.savings)}</strong></article><article className="allocationCard allocationWants"><Sparkles/><span>Desideri · {year.percentages.wants}%</span><strong>{money(current.wants)}</strong></article></div></>}
   {view==="year"&&<><div className="kpiGrid"><Kpi icon={<WalletCards/>} label="Entrate totali" value={money(annual.total)} tone="income"/><Kpi icon={<CircleDollarSign/>} label="Stipendi" value={money(annual.salary)} tone="salary"/><Kpi icon={<Plus/>} label="Extra" value={money(annual.extra)} tone="extra"/><Kpi icon={<Landmark/>} label="Essenziali" value={money(annual.essential)} tone="essential"/><Kpi icon={<PiggyBank/>} label="Risparmi" value={money(annual.savings)} tone="savings"/><Kpi icon={<Sparkles/>} label="Desideri" value={money(annual.wants)} tone="wants"/></div>
    <ChartCard title="Entrate mensili" sub="Stipendio + entrate extra"><ResponsiveContainer width="100%" height="100%"><BarChart data={annualChart}><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>money(v)}/><Bar dataKey="entrate" fill="var(--chart-color-1)" radius={[6,6,2,2]}/></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Risparmi cumulativi" sub="Quanto hai destinato ai risparmi durante l'anno"><ResponsiveContainer width="100%" height="100%"><LineChart data={cumulativeChart}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>money(v)}/><Line type="monotone" dataKey="risparmi" stroke="var(--chart-color-1)" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard>
    <div className="sectionTitle"><h2>Dettaglio mesi</h2></div><div className="monthList">{year.months.map((m,i)=>{const c=calcMonth(year,m);return <button key={i} onClick={()=>{setMonthIndex(i);setView("home")}}><span>{monthNames[i]}</span><span>{money(c.total)}</span><b>{money(c.savings)}</b></button>})}</div></>}
   {view==="history"&&<><section className="hero"><div className="heroTop"><span>Dal primo anno registrato</span><span className="statusPill">STORICO</span></div><div className="heroAmount">{money(historySavings)}</div><div className="heroBreakdown">Risparmi complessivi</div></section><ChartCard title="Andamento annuale" sub="Entrate e risparmi per anno"><ResponsiveContainer width="100%" height="100%"><BarChart data={historyData}><XAxis dataKey="year" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>money(v)}/><Bar dataKey="entrate" fill="var(--chart-color-2)" radius={[5,5,2,2]}/><Bar dataKey="risparmi" fill="var(--chart-color-1)" radius={[5,5,2,2]}/></BarChart></ResponsiveContainer></ChartCard><div className="sectionTitle"><h2>Anni</h2></div><div className="yearList">{historyData.map(x=><button key={x.year} onClick={()=>{setSelectedYear(x.year);setView("year")}}><span><b>{x.year}</b><small>{data.years[x.year].percentages.essential}/{data.years[x.year].percentages.savings}/{data.years[x.year].percentages.wants}</small></span><span><small>Entrate</small><b>{money(x.entrate)}</b></span><span><small>Risparmi</small><b className="savingsValue">{money(x.risparmi)}</b></span></button>)}</div></>}
   {view==="settings"&&<><section className="settingsCard"><div className="settingsHead"><h2>Regola budget {selectedYear}</h2><p>Le percentuali restano legate esclusivamente a questo anno.</p></div><PercentRow label="Essenziale" hint="Casa, bollette e spese necessarie" value={pct.essential} onChange={v=>setPct({...pct,essential:v})}/><PercentRow label="Risparmi" hint="Accantonamento e investimenti" value={pct.savings} onChange={v=>setPct({...pct,savings:v})} accent/><PercentRow label="Desideri" hint="Svago e spese non essenziali" value={pct.wants} onChange={v=>setPct({...pct,wants:v})}/><div className="percentTotal"><span>Totale</span><b className={pct.essential+pct.savings+pct.wants===100?"ok":"bad"}>{pct.essential+pct.savings+pct.wants}%</b></div><button className="btn wide" onClick={savePercentages}><CheckCircle2 size={18}/>Salva percentuali</button><button className="btn outline wide" onClick={copyPrevious}><Copy size={16}/>Copia dall'anno precedente</button></section>
    <section className="settingsCard"><div className="toggleLine"><div><h3>Extra interamente nei risparmi</h3><p>Replica il comportamento del tracker originale.</p></div><button className={year.extrasToSavings?"switch checked":"switch"} onClick={()=>updateYear(y=>({...y,extrasToSavings:!y.extrasToSavings}))}><span/></button></div></section>
    <section className="settingsCard"><div className="settingsHead"><h2>Backup</h2><p>I dati restano su questo dispositivo. Puoi esportarne una copia quando vuoi.</p></div><button className="btn outline wide" onClick={exportBackup}><Download size={17}/>Esporta backup JSON</button><button className="btn outline wide" onClick={importRestoreCode}><Copy size={16}/>Ripristina da codice</button></section>
    <section className="settingsCard"><div className="settingsHead"><h2>Gestione anno</h2><p>Elimina solo i dati dell'anno selezionato.</p></div><button className="btn destructive wide" onClick={deleteYear}><Trash2 size={16}/>Elimina anno {selectedYear}</button></section></>}
  </main>
  <nav className="nav"><Nav active={view==="home"} icon={<Home/>} label="Home" onClick={()=>setView("home")}/><Nav active={view==="year"} icon={<CalendarRange/>} label="Anno" onClick={()=>setView("year")}/><Nav active={view==="history"} icon={<TrendingUp/>} label="Storico" onClick={()=>setView("history")}/><Nav active={view==="settings"} icon={<Settings/>} label="Impostazioni" onClick={()=>setView("settings")}/></nav>
  {extraOpen&&<div className="modalBackdrop" onMouseDown={()=>setExtraOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modalClose iconBtn" onClick={()=>setExtraOpen(false)}><X/></button><h2>Nuova entrata extra</h2><p>{monthNames[monthIndex]} {selectedYear}</p><label>Importo<input type="number" inputMode="decimal" min="0" step=".01" value={extraAmount} onChange={e=>setExtraAmount(e.target.value)} placeholder="0,00"/></label><label>Descrizione<input value={extraDescription} onChange={e=>setExtraDescription(e.target.value)} placeholder="Straordinari, vendita, rimborso…"/></label><label>Data<input type="date" value={extraDate} onChange={e=>setExtraDate(e.target.value)}/></label><button className="btn wide large" onClick={addExtra}><Plus size={17}/>Aggiungi entrata</button></div></div>}
  {notice&&<div className="notice">{notice}</div>}
 </div>
}
function Nav({active,icon,label,onClick}){return <button className={active?"navActive":"navButton"} onClick={onClick}>{icon}<span>{label}</span></button>}
function Kpi({icon,label,value,tone}){return <article className={"kpi kpi"+tone[0].toUpperCase()+tone.slice(1)}><span className="kpiIcon">{icon}</span><small>{label}</small><strong>{value}</strong></article>}
function PercentRow({label,hint,value,onChange,accent}){return <div className="percentRow"><div><span className={accent?"dotAccent":"dot"}/><span><b>{label}</b><small>{hint}</small></span></div><div className="percentInput"><input type="number" min="0" max="100" value={value} onChange={e=>onChange(Number(e.target.value))}/><span>%</span></div></div>}
function ChartCard({title,sub,children}){return <section className="chartCard"><div className="chartHead"><div><h2>{title}</h2><p>{sub}</p></div></div><div className="chart">{children}</div></section>}
